Fix tracy tools build: need to link pthread to avoid undefined reference to `pthread_create' - also fix TracyClient build (get rid of redef of AllocSourceLocation)